// auto-generated by lnp-tbox.sage.
// 
// protocol is statistically complete with correctness error >= 1 - 2^(-3)
// protocol is simulatable under MLWE(34,24,[-1,1])
// protocol is knowledge-sound with knowledge error <= 2^(-127.0) under MSIS(12,66,2^(31.975233))
// 
// Ring
// degree d = 64
// modulus q = 9007199254743517, log(q) ~ 53.0
// factors q = q1
// 
// Compression
// D = 7
// gamma = 52578, log(gamma) ~ 15.682172
// 
// Dimensions of secrets
// s1: m1 = 8
// m: l = 0
// s2: m2 = 58
// 
// Size of secrets
// l2(s1) <= alpha = 46.0
// m unbounded
// s2 uniform in [-nu,nu] = [-1,1]
// 
// Norm proofs
// binary: no
// exact euclidean: yes (dimensions: [8], bounds: [45.254834])
// approximate infinity: yes (psi: 3350.9656, dimension: 4, bound: 256.5)
// 
// Challenge space
// c uniform in [-omega,omega] = [-8,8], o(c)=c, sqrt(l1(o(c)*c)) <= eta = 140
// 
// Standard deviations
// stdev1 = 101580.8, log(stdev1/1.55) = 16.0
// stdev2 = 6348.8, log(stdev2/1.55) = 12.0
// stdev3 = 3174.4, log(stdev3/1.55) = 11.0
// stdev4 = 25395.2, log(stdev4/1.55) = 14.0
// 
// Repetition rate
// M1 = 2.3693196
// M2 = 2.465778
// M3 = 1.0359469
// M4 = 1.0173384
// total = 6.1571619
// 
// Security
// MSIS dimension: 12
// MSIS root hermite factor: 1.0043622
// MLWE dimension: 34
// MLWE root hermite factor: 1.0042981
// 
// Proof size
// ~ 18.7500000000000 KiB
// 
// 50 bit moduli for degree 64: [1125899906840833, 1125899906839937, 1125899906837633]
// bit length of products: [49, 99, 149]
// inverses: [1, -162099428551732, 296975494591860]

#include "lazer.h"
static const limb_t _param_q_limbs[] = {9007199254743517UL};
static const int_t _param_q = {{(limb_t *)_param_q_limbs, 1, 0}};
static const limb_t _param_qminus1_limbs[] = {9007199254743516UL};
static const int_t _param_qminus1 = {{(limb_t *)_param_qminus1_limbs, 1, 0}};
static const limb_t _param_m_limbs[] = {171311180622UL};
static const int_t _param_m = {{(limb_t *)_param_m_limbs, 1, 0}};
static const limb_t _param_mby2_limbs[] = {85655590311UL};
static const int_t _param_mby2 = {{(limb_t *)_param_mby2_limbs, 1, 0}};
static const limb_t _param_gamma_limbs[] = {52578UL};
static const int_t _param_gamma = {{(limb_t *)_param_gamma_limbs, 1, 0}};
static const limb_t _param_gammaby2_limbs[] = {26289UL};
static const int_t _param_gammaby2 = {{(limb_t *)_param_gammaby2_limbs, 1, 0}};
static const limb_t _param_pow2D_limbs[] = {128UL};
static const int_t _param_pow2D = {{(limb_t *)_param_pow2D_limbs, 1, 0}};
static const limb_t _param_pow2Dby2_limbs[] = {64UL};
static const int_t _param_pow2Dby2 = {{(limb_t *)_param_pow2Dby2_limbs, 1, 0}};
static const limb_t _param_Bsq_limbs[] = {2322205048513UL, 0UL};
static const int_t _param_Bsq = {{(limb_t *)_param_Bsq_limbs, 2, 0}};
static const limb_t _param_scM1_limbs[] = {2804632486965449207UL, 6812745002331132667UL, 2UL};
static const int_t _param_scM1 = {{(limb_t *)_param_scM1_limbs, 3, 0}};
static const limb_t _param_scM2_limbs[] = {10189608724252333762UL, 8592086691763836887UL, 2UL};
static const int_t _param_scM2 = {{(limb_t *)_param_scM2_limbs, 3, 0}};
static const limb_t _param_scM3_limbs[] = {8893015289224868487UL, 663103872151883249UL, 1UL};
static const int_t _param_scM3 = {{(limb_t *)_param_scM3_limbs, 3, 0}};
static const limb_t _param_scM4_limbs[] = {14779455052103325281UL, 319837337030417186UL, 1UL};
static const int_t _param_scM4 = {{(limb_t *)_param_scM4_limbs, 3, 0}};
static const limb_t _param_stdev1sq_limbs[] = {10318658929UL, 0UL};
static const int_t _param_stdev1sq = {{(limb_t *)_param_stdev1sq_limbs, 2, 0}};
static const limb_t _param_stdev2sq_limbs[] = {40307261UL, 0UL};
static const int_t _param_stdev2sq = {{(limb_t *)_param_stdev2sq_limbs, 2, 0}};
static const limb_t _param_stdev3sq_limbs[] = {10076815UL, 0UL};
static const int_t _param_stdev3sq = {{(limb_t *)_param_stdev3sq_limbs, 2, 0}};
static const limb_t _param_stdev4sq_limbs[] = {644916183UL, 0UL};
static const int_t _param_stdev4sq = {{(limb_t *)_param_stdev4sq_limbs, 2, 0}};
static const limb_t _param_inv2_limbs[] = {4503599627371758UL};
static const int_t _param_inv2 = {{(limb_t *)_param_inv2_limbs, 1, 1}};
static const limb_t _param_inv4_limbs[] = {2251799813685879UL};
static const int_t _param_inv4 = {{(limb_t *)_param_inv4_limbs, 1, 1}};
static const unsigned int _param_n[1] = {8};
static const limb_t _param_Bz3sqr_limbs[] = {6938266263UL, 0UL};
static const int_t _param_Bz3sqr = {{(limb_t *)_param_Bz3sqr_limbs, 2, 0}};
static const limb_t _param_Bz4_limbs[] = {406323UL};
static const int_t _param_Bz4 = {{(limb_t *)_param_Bz4_limbs, 1, 0}};
static const limb_t _param_Pmodq_limbs[] = {3676733316732247UL};
static const int_t _param_Pmodq = {{(limb_t *)_param_Pmodq_limbs, 1, 0}};
static const limb_t _param_l2Bsq0_limbs[] = {2048UL};
static const int_t _param_l2Bsq0 = {{(limb_t *)_param_l2Bsq0_limbs, 1, 0}};
static const limb_t _param_Ppmodq_0_limbs[] = {1829587332685972UL};
static const int_t _param_Ppmodq_0 = {{(limb_t *)_param_Ppmodq_0_limbs, 1, 1}};
static const limb_t _param_Ppmodq_1_limbs[] = {1829587337440708UL};
static const int_t _param_Ppmodq_1 = {{(limb_t *)_param_Ppmodq_1_limbs, 1, 1}};
static const limb_t _param_Ppmodq_2_limbs[] = {1829587342294372UL};
static const int_t _param_Ppmodq_2 = {{(limb_t *)_param_Ppmodq_2_limbs, 1, 1}};
static const int_srcptr _param_l2Bsq[] = {_param_l2Bsq0};
static const int_srcptr _param_Ppmodq[] = {_param_Ppmodq_0, _param_Ppmodq_1, _param_Ppmodq_2};
static const polyring_t _param_ring = {{_param_q, 64, 54, 6, moduli_d64, 3, _param_Pmodq, _param_Ppmodq, _param_inv2}};
static const dcompress_params_t _param_dcomp = {{ _param_q, _param_qminus1, _param_m, _param_mby2, _param_gamma, _param_gammaby2, _param_pow2D, _param_pow2Dby2, 7, 0, 38 }};
static const abdlop_params_t _param_tbox = {{ _param_ring, _param_dcomp, 9, 58, 0, 12, 12, _param_Bsq, 1, 8, 5, 140, 1, 16, _param_scM1, _param_stdev1sq, 2, 12, _param_scM2, _param_stdev2sq}};
static const abdlop_params_t _param_quad_eval_ = {{ _param_ring, _param_dcomp, 9, 58, 9, 3, 12, _param_Bsq, 1, 8, 5, 140, 1, 16, _param_scM1, _param_stdev1sq, 2, 12, _param_scM2, _param_stdev2sq}};
static const abdlop_params_t _param_quad_many_ = {{ _param_ring, _param_dcomp, 9, 58, 11, 1, 12, _param_Bsq, 1, 8, 5, 140, 1, 16, _param_scM1, _param_stdev1sq, 2, 12, _param_scM2, _param_stdev2sq}};
static const lnp_quad_eval_params_t _param_quad_eval = {{ _param_quad_eval_, _param_quad_many_, 4}};
static const lnp_tbox_params_t _param = {{ _param_tbox, _param_quad_eval, 0, _param_n, 4, 1, 9, 2, 11, _param_scM3, _param_stdev3sq, 2, 14, _param_scM4, _param_stdev4sq, _param_Bz3sqr, _param_Bz4, &_param_l2Bsq[0], _param_inv4, 19200UL }};

